[package]
name = "amoru-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Amoru test fakes for every contracts interface"

[dependencies]
amoru-kernel = { workspace = true }

[features]
default = []
